import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navigation from '@/app/ui/shared/navigation';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col md:flex-row">
            <div className="md:w-64">
            {/* Sidebar Component Here */}
            <Navigation />
            </div>
            <div className="flex-1">
              {/* Main Content Here */}
              {children}
            </div>
        </div>
      </body>
    </html>
  )
}
